# Generated by Django 4.0.3 on 2022-04-05 11:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0003_rename_flag_unregisteredusers_issuedticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('license', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='unregisteredusers',
            name='issuedTicket',
        ),
    ]
